In [1]:
import pandas as pd

In [12]:
banks = pd.read_csv("C:/Users/Dell/OneDrive/Desktop/TOPS/assessments/assessment/n,p,assess.csv")
banks

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,26-Jul-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,26-Jul-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,26-Jul-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17
...,...,...,...,...,...,...,...
548,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB",27-Jul-01,19-Aug-14
549,Malta National Bank,Malta,OH,6629,North Valley Bank,3-May-01,18-Nov-02
550,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,2-Feb-01,18-Feb-03
551,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,14-Dec-00,17-Mar-05
552,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,13-Oct-00,17-Mar-05

In [13]:
#head of dataset

banks.head(10)

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Fayette County Bank,Saint Elmo,IL,1802,"United Fidelity Bank, fsb",26-May-17,26-Jul-17
1,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,WI,30003,First-Citizens Bank & Trust Company,5-May-17,26-Jul-17
2,First NBC Bank,New Orleans,LA,58302,Whitney Bank,28-Apr-17,26-Jul-17
3,Proficio Bank,Cottonwood Heights,UT,35495,Cache Valley Bank,3-Mar-17,18-May-17
4,Seaway Bank and Trust Company,Chicago,IL,19328,State Bank of Texas,27-Jan-17,18-May-17
5,Harvest Community Bank,Pennsville,NJ,34951,First-Citizens Bank & Trust Company,13-Jan-17,18-May-17
6,Allied Bank,Mulberry,AR,91,Today's Bank,23-Sep-16,17-Nov-16
7,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,19-Aug-16,1-Jun-17
8,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,6-May-16,6-Sep-16
9,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,29-Apr-16,6-Sep-16

In [14]:
banks.tail()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
548,"Superior Bank, FSB",Hinsdale,IL,32646,"Superior Federal, FSB",27-Jul-01,19-Aug-14
549,Malta National Bank,Malta,OH,6629,North Valley Bank,3-May-01,18-Nov-02
550,First Alliance Bank & Trust Co.,Manchester,NH,34264,Southern New Hampshire Bank & Trust,2-Feb-01,18-Feb-03
551,National State Bank of Metropolis,Metropolis,IL,3815,Banterra Bank of Marion,14-Dec-00,17-Mar-05
552,Bank of Honolulu,Honolulu,HI,21029,Bank of the Orient,13-Oct-00,17-Mar-05

In [15]:
banks.columns

Index(['Bank Name', 'City', 'ST', 'CERT', 'Acquiring Institution',
       'Closing Date', 'Updated Date'],
      dtype='object')

In [16]:
#

banks.describe()

               CERT
count    553.000000
mean   31729.652803
std    16420.594894
min       91.000000
25%    20340.000000
50%    32218.000000
75%    35372.000000
max    58701.000000

In [17]:

banks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 553 entries, 0 to 552
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Bank Name              553 non-null    object
 1   City                   553 non-null    object
 2   ST                     553 non-null    object
 3   CERT                   553 non-null    int64
 4   Acquiring Institution  553 non-null    object
 5   Closing Date           553 non-null    object
 6   Updated Date           553 non-null    object
dtypes: int64(1), object(6)
memory usage: 30.4+ KB

In [35]:
#LIST OF STATES

x=banks['ST'].unique().tolist()
x

['IL',
 'WI',
 'LA',
 'UT',
 'NJ',
 'AR',
 'GA',
 'PA',
 'TN',
 'WA',
 'CO',
 'PR',
 'FL',
 'MN',
 'CA',
 'MD',
 'OK',
 'OH',
 'SC',
 'VA',
 'ID',
 'TX',
 'CT',
 'AZ',
 'NV',
 'NC',
 'KY',
 'MO',
 'KS',
 'AL',
 'MI',
 'IN',
 'IA',
 'NE',
 'MS',
 'NM',
 'OR',
 'NY',
 'MA',
 'SD',
 'WY',
 'WV',
 'NH',
 'HI']

In [34]:
#TOP 5 STATES WITH MOST FAILED BANKS

banks['ST'].value_counts().head(5)

ST
GA    93
FL    75
IL    68
CA    41
MN    23
Name: count, dtype: int64

In [36]:
#TOP 5 acquiring institutions?

banks['Acquiring Institution'].value_counts().head(5)

Acquiring Institution
No Acquirer                            31
State Bank and Trust Company           12
First-Citizens Bank & Trust Company    11
Ameris Bank                            10
U.S. Bank N.A.                          9
Name: count, dtype: int64

In [55]:
fil_data=banks['Acquiring Institution']== 'State Bank of Texas'
fil_data.sum()

np.int64(3)

In [56]:
in_texas=banks['ST']=='TX'
in_texas.sum()

np.int64(12)

In [57]:
final=fil_data.sum()&in_texas.sum()
final

np.int64(0)

In [67]:
Y=banks[banks['ST']=='CA']

In [68]:
Y['City'].value_counts().idxmax()

'Chicago'